const data = [
    {
      id: 1,
      name: "12/28/2021",
      age: "This is largely due to high food inflation, particularly meat, and increased transport inflation amid soaring oil prices.",
      color: "high food inflation",
      dob: "increase"
    },
    {
      id: 2,
      name: "12/28/2021",
      age: "This is largely due to high food inflation, particularly meat, and increased transport inflation amid soaring oil prices.",
      color: "increased transport inflation",
      dob: "decrease"
    },
    {
      id: 5,
      name: "12/28/2021",
      age: "Continued pandemic worries aside, the US Federal Reserve's (Fed) hawkish pivot to tame inflation is exacerbating the situation.",
      color: "tame inflation",
      dob: "decrease",
    },
    {
      id: 6,
      name: "12/29/2021",
      age: "Most investments lose value during high inflation, and Agilent is a rare exception.",
      color: "high inflation",
      dob: "increase",
    },
    {
      id: 7,
      name: "12/29/2021",
      age: "The increase is higher than it's been in recent years due to higher inflation, Labor Commissioner Laurie Esau said when she announced the change in September.",
      color: "higher inflation",
      dob: "increase",
    },
    {
        id: 8,
        name: "12/30/2021",
        age: "Consumers are eager to continue the tradition of sales shopping, despite rising inflation and concerns about the new COVID-19 variant.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 9,
        name: "12/30/2021",
        age: "As such, inflation is mitigated until there is the appropriate TVL to utilize the introduction of the locked tokens.",
        color: "inflation is mitigated",
        dob: "decrease",
      },
      {
        id: 10,
        name: "1/1/2022",
        age: "And rising inflation is making a dent in all of our wallets.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 11,
        name: "1/3/2022",
        age: "Monetary measures, like higher interest rates, would help tame a demand-pull inflation.",
        color: "help tame a demand-pull inflation",
        dob: "decrease",
      },
      {
        id: 12,
        name: "1/3/2022",
        age: "And rising inflation is making a dent in all of our wallets.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 13,
        name: "1/3/2022",
        age: "Interestingly, the IMF and World Bank both issued warnings over rising inflation.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 14,
        name: "1/3/2022",
        age: "Or will the combination of rising inflation and tighter monetary policy end the bull run?",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 15,
        name: "1/3/2022",
        age: "The gains, however, are likely to be smaller as the Federal Reserve winds down its pandemic-era monetary support to tame inflation.",
        color: "tame inflation",
        dob: "decrease",
      },
      {
        id: 16,
        name: "1/3/2022",
        age: "This week's falls have eroded the big gains the lira made a week earlier as investors fret about the country's unorthodox monetary policy and rising inflation, and that President Tayyip Erdogan's plan to defend lira deposits unveiled this month won't work.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 17,
        name: "1/3/2022",
        age: "Plenty of economic challenges persist, including rising inflation, global supply chain disruptions and outbreaks of more contagious variants of the COVID-19 virus.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 18,
        name: "1/3/2022",
        age: "I think by the second half of next year, you'll be seeing that inflation being tamed quite a bit.",
        color: "inflation being tamed",
        dob: "decrease",
      },
      {
        id: 15,
        name: "1/3/2022",
        age: "The gains, however, are likely to be smaller as the Federal Reserve winds down its pandemic-era monetary support to tame inflation.",
        color: "tame inflation",
        dob: "decrease",
      },
      {
        id: 16,
        name: "1/3/2022",
        age: "This week's falls have eroded the big gains the lira made a week earlier as investors fret about the country's unorthodox monetary policy and rising inflation, and that President Tayyip Erdogan's plan to defend lira deposits unveiled this month won't work.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 11,
        name: "1/3/2022",
        age: "Monetary measures, like higher interest rates, would help tame a demand-pull inflation.",
        color: "help tame a demand-pull inflation",
        dob: "decrease",
      },
      {
        id: 12,
        name: "1/3/2022",
        age: "And rising inflation is making a dent in all of our wallets.",
        color: "rising inflation",
        dob: "increase",
      },
      {
        id: 7,
        name: "12/29/2021",
        age: "The increase is higher than it's been in recent years due to higher inflation, Labor Commissioner Laurie Esau said when she announced the change in September.",
        color: "higher inflation",
        dob: "increase",
      },
      {
          id: 8,
          name: "12/30/2021",
          age: "Consumers are eager to continue the tradition of sales shopping, despite rising inflation and concerns about the new COVID-19 variant.",
          color: "rising inflation",
          dob: "increase",
        },
        {
          id: 9,
          name: "12/30/2021",
          age: "As such, inflation is mitigated until there is the appropriate TVL to utilize the introduction of the locked tokens.",
          color: "inflation is mitigated",
          dob: "decrease",
        },
        {
          id: 10,
          name: "1/1/2022",
          age: "And rising inflation is making a dent in all of our wallets.",
          color: "rising inflation",
          dob: "increase",
        },
        {
          id: 2,
          name: "12/28/2021",
          age: "This is largely due to high food inflation, particularly meat, and increased transport inflation amid soaring oil prices.",
          color: "increased transport inflation",
          dob: "decrease"
        },
        {
          id: 5,
          name: "12/28/2021",
          age: "Continued pandemic worries aside, the US Federal Reserve's (Fed) hawkish pivot to tame inflation is exacerbating the situation.",
          color: "tame inflation",
          dob: "decrease",
        },
        {
          id: 6,
          name: "12/29/2021",
          age: "Most investments lose value during high inflation, and Agilent is a rare exception.",
          color: "high inflation",
          dob: "increase",
        },
        {
          id: 7,
          name: "12/29/2021",
          age: "The increase is higher than it's been in recent years due to higher inflation, Labor Commissioner Laurie Esau said when she announced the change in September.",
          color: "higher inflation",
          dob: "increase",
        },
        {
            id: 8,
            name: "12/30/2021",
            age: "Consumers are eager to continue the tradition of sales shopping, despite rising inflation and concerns about the new COVID-19 variant.",
            color: "rising inflation",
            dob: "increase",
          },
          {
            id: 9,
            name: "12/30/2021",
            age: "As such, inflation is mitigated until there is the appropriate TVL to utilize the introduction of the locked tokens.",
            color: "inflation is mitigated",
            dob: "decrease",
          }
  ];
  

  export default data;